### ISSUE TITLE
TODO : Mod Center API integration

### ISSUE THREAD

**Issue by skyecodes** [Franckyi/Mod-Center-Client#1]
- [x] Replace ModLogical with API Project
- [x] Replace ModVisual with new ProjectVisual
- [x] Rewrite SortFilter
- [x] Move MCVersion and SortFilter to API
- [x] Add "number of items per page" configuration
- [x] Change SelectModTable according to API ProjectFile
- [x] Category selection
- [x] Some other tweaks
