### ISSUE TITLE
TODO : First release

### ISSUE THREAD

**Issue by skyecodes** [Franckyi/Mod-Center-Client#2]
- [x] Finish Mod Center API integration ( #1 )
- [ ] Move downloads in a tab instead of in a second window
- [ ] Resolve dependencies
- [ ] "My mods" section, updater (from API)
- [ ] "My modpacks" section
- [ ] More config
- [x] Logo and design
- [x] Rename / Move repository and application
